from colorama import Fore, init, Style
from os import listdir, rmdir, walk
from os.path import isdir, join, exists

bright = Style.BRIGHT
green, red,blue, reset = Fore.GREEN + bright, Fore.RED + bright,Fore.BLUE + bright, Fore.RESET
init(convert=True, autoreset=True)


def delete_empty_folders(path):
    for subdir, dirs, files in walk(path,topdown=False):
        for dir in dirs:
            full_path = join(subdir, dir)
            if not listdir(full_path):
                print(f"{red}[-] Deleting empty folder - {full_path}")
                rmdir(full_path)
    if not listdir(path):
        print(f"{red}[-] Deleting empty folder - {path}")
        rmdir(path)

def credit():
    credit_text = f"""
               {red}DELETE EMPTY FOLDERS
{green}               
     ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
    ▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
    ▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
    ▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
    ░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
    ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
      ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
      ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
       ░           ░  ░ ░  ░  ░   ░         ░  ░ {blue}code generated by Rahul.p\n
    """
    print(credit_text)
    

credit()
path = input("[+] Enter path or drag and drop the folder : ").replace('"','')
if path=='':
    path = input("[+] Enter path or drag and drop the folder : ").replace('"','')
print(f"{green}[+] Deleting empty folders")
if exists(path) and isdir(path):
    delete_empty_folders(path)
else:
    print(f"{red}[-] Error: {path} not found or permission denied.")

